name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'www/**'
      - 'src/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Lib Dependencies
        run: npm ci

      - name: Install Peers Dependencies
        run: npm run install:peers

      - name: Install Docs Dependencies
        run: npm ci
        working-directory: www

      - name: Parse TSDoc Documentation
        run: npm run docs:generate

      - name: Build Docs
        run: npm run build
        working-directory: www

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/build

      # We don't know when the site will be deployed, we just wait a few seconds
      # Better solutions can be found
      - name: Sleep for 30s
        run: sleep 30

      - name: Github-pages-MAIN => Algolia crawler creation and recrawl (Push on Main branch)
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://viniciusl.com.br/serverless-adapter/'
