name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN_GITHUB }}
          release-type: node
          changelog-types: >
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "build", "section": "Build Related", "hidden": false },
              { "type": "chore", "section": "Chores", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "ci", "section": "CI", "hidden": false },
              { "type": "refactor", "section": "Refactoring", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]

      - name: Checkout Code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Deps
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Get Coverage Info
        if: ${{ steps.release.outputs.release_created }}
        run: npm run coverage

      - name: NPM Publish
        run: npm publish --provenance --access public
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
